# Generated by Django 3.2.7 on 2021-10-04 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_task_day'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='remainder',
            new_name='reminder',
        ),
    ]
