# Generated by Django 3.1.1 on 2021-01-09 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='item',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
