# Generated by Django 3.1.1 on 2021-01-10 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20210109_1105'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='item',
            new_name='content',
        ),
    ]
