# Generated by Django 3.1.1 on 2021-01-01 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='usern',
            new_name='user',
        ),
    ]
