# Generated by Django 3.2.7 on 2021-10-07 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='title',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='expense',
            name='Date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
