# Generated by Django 3.2.7 on 2021-10-07 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_auto_20211007_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='Date',
            field=models.DateField(),
        ),
    ]
