# Generated by Django 3.2.7 on 2021-10-07 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_alter_expense_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='Date',
            field=models.DateField(auto_now=True),
        ),
    ]
